/* SPDX-License-Identifier: GPL-2.0 */
#ifndef _LINUX_ORCHESTRATOR_STATS_H
#define _LINUX_ORCHESTRATOR_STATS_H
/*
 *  Header containing orchestrator stat definitions
 *
 *  Copyright (C) 2025 Meta Platforms, Inc. and affiliates
 */

#include <linux/bug.h>
#include <linux/sched.h>
#include <linux/types.h>

/*
 * All of this could be autogenerated using macros and tables if we used the
 * ANDROID_VENDOR_DATA_ARRAY embedded in struct task_struct to store the struct
 * orchestrator, but if we did that, we wouldn't be able to view its contents
 * in bpftrace as the bpf verifier won't allow us to cast from a u64[] to a
 * struct orchestrator.
 *
 * Instead, let's just manually add stat events for now. In order to add a new
 * stat event you must:
 *
 * 1. Add an entry to struct orchestrator_stats in linux/orchestrator_types.h
 * 2. Add an entry to this enum
 * 3. Add an entry to the switch statement in orchestrator_stat_event_inc()
 * 4. Call orchestrator_stat_event_inc() from wherever you need elsewhere in
 *    the orchestrator agent.
 */
enum orchestator_stat_event {
	NR_SRQ_PREV,
	NR_SRQ_SYNC,
	NR_SRQ_ANY,
};

#ifdef CONFIG_ORCHESTRATOR_AGENT_STATS
static inline void orchestrator_stat_event_inc(struct task_struct *p,
					       enum orchestator_stat_event event)
{
	struct orchestrator_stats *stats = &p->orchestrator.stats;

	switch (event) {
		case NR_SRQ_PREV:
			stats->nr_srq_prev++;
			break;
		case NR_SRQ_SYNC:
			stats->nr_srq_sync++;
			break;
		case NR_SRQ_ANY:
			stats->nr_srq_any++;
			break;
		default:
			BUG();
	}
}
#else
static inline void orchestrator_stat_event_inc(struct task_struct *p,
					       enum orchestator_stat_event event)
{}
#endif

#endif /* _LINUX_ORCHESTRATOR_STATS_H */
