#ifndef _SWD_REGISTERS_SAMD_H
#define _SWD_REGISTERS_SAMD_H

#define SWD_SAMD_NVMCTRL_BASE		0x41004000
#define SWD_SAMD_NVMCTRL_CTRLA		(SWD_SAMD_NVMCTRL_BASE + 0x00)
#define SWD_SAMD_NVMCTRL_CTRLB		(SWD_SAMD_NVMCTRL_BASE + 0x04)
#define SWD_SAMD_NVMCTRL_PARAM		(SWD_SAMD_NVMCTRL_BASE + 0x08)
#define SWD_SAMD_NVMCTRL_INTFLAG	(SWD_SAMD_NVMCTRL_BASE + 0x14)
#define SWD_SAMD_NVMCTRL_STATUS		(SWD_SAMD_NVMCTRL_BASE + 0x18)
#define SWD_SAMD_NVMCTRL_ADDR		(SWD_SAMD_NVMCTRL_BASE + 0x1C)

#define SWD_SAMD_NVMCTRL_INTFLAG_READY	0x01
#define SWD_SAMD_NVMCTRL_INTFLAG_ERROR	0x02

#define SWD_SAMD_NVMCTRL_CTRLA_CMD_ER	0xA502
#define SWD_SAMD_NVMCTRL_CTRLA_CMD_WP	0xA504
#define SWD_SAMD_NVMCTRL_CTRLA_CMD_EAR	0xA505
#define SWD_SAMD_NVMCTRL_CTRLA_CMD_WAP	0xA506
#define SWD_SAMD_NVMCTRL_CTRLA_CMD_LR	0xA540
#define SWD_SAMD_NVMCTRL_CTRLA_CMD_UR	0xA541
#define SWD_SAMD_NVMCTRL_CTRLA_CMD_PBC	0xA544

#define SWD_SAMD_NVMCTRL_CTRLB_MANW	(1 << 7)

#define SWD_SAMD_DSU_BASE		    0x41002100
#define SWD_SAMD_DSU_CTRL		    (SWD_SAMD_DSU_BASE + 0x00)
#define SWD_SAMD_DSU_STATUSA		(SWD_SAMD_DSU_BASE + 0x01)
#define SWD_SAMD_DSU_STATUSB		(SWD_SAMD_DSU_BASE + 0x02)
#define SWD_SAMD_DSU_ADDR		    (SWD_SAMD_DSU_BASE + 0x04)

#define SWD_SAMD_DSU_CTRL_SWRST		0x01
#define SWD_SAMD_DSU_CTRL_CE		0x10

#define SWD_SAMD_DSU_STATUSA_DONE	0x01

#define SWD_SAMD_NVM_USER_ROW_W0	0x00804000
#define SWD_SAMD_NVM_USER_ROW_W1	0x00804004
#define SWD_SAMD_NVM_EEPROM_SIZE_SHIFT	4
#define SWD_SAMD_NVM_EEPROM_SIZE_MASK	(0x7 << SWD_SAMD_NVM_EEPROM_SIZE_SHIFT)

#define SWD_SAMD_NVM_EEPROM_SIZE	0x00000400
#define SWD_SAMD_NVM_EEPROM_SIZE_VAL	4
#define SWD_SAMD_NVM_EEPROM_BASE	0x0001FC00

#endif
