# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_VIDEO_MXB) += mxb.o
obj-$(CONFIG_VIDEO_HEXIUM_unknown5) += hexium_unknown5.o
obj-$(CONFIG_VIDEO_HEXIUM_GEMINI) += hexium_gemini.o

ccflags-y += -I$(srctree)/drivers/media/i2c
