#ifndef _SWD_REGISTERS_SAMD_H
#define _SWD_REGISTERS_SAMD_H

#define SWD_SAMD_NVMCTRL_BASE		0x41004000
#define SWD_SAMD_NVMCTRL_CTRLA		(SWD_SAMD_NVMCTRL_BASE + 0x00)
#define SWD_SAMD_NVMCTRL_CTRLB		(SWD_SAMD_NVMCTRL_BASE + 0x04)
#define SWD_SAMD_NVMCTRL_PARAM		(SWD_SAMD_NVMCTRL_BASE + 0x08)
#define SWD_SAMD_NVMCTRL_INTFLAG	(SWD_SAMD_NVMCTRL_BASE + 0x14)
#define SWD_SAMD_NVMCTRL_STATUS		(SWD_SAMD_NVMCTRL_BASE + 0x18)
#define SWD_SAMD_NVMCTRL_ADDR		(SWD_SAMD_NVMCTRL_BASE + 0x1C)

#define SWD_SAMD_NVMCTRL_INTFLAG_READY	0x01
#define SWD_SAMD_NVMCTRL_INTFLAG_ERROR	0x02

#define SWD_SAMD_NVMCTRL_CTRLA_CMD_ER	0xA502
#define SWD_SAMD_NVMCTRL_CTRLA_CMD_WP	0xA504
#define SWD_SAMD_NVMCTRL_CTRLA_CMD_UR	0xA541
#define SWD_SAMD_NVMCTRL_CTRLA_CMD_PBC	0xA544

#define SWD_SAMD_DSU_BASE		    0x41002100
#define SWD_SAMD_DSU_CTRL		    (SWD_SAMD_DSU_BASE + 0x00)
#define SWD_SAMD_DSU_STATUSA		(SWD_SAMD_DSU_BASE + 0x01)
#define SWD_SAMD_DSU_STATUSB		(SWD_SAMD_DSU_BASE + 0x02)
#define SWD_SAMD_DSU_ADDR		    (SWD_SAMD_DSU_BASE + 0x04)

#define SWD_SAMD_DSU_CTRL_SWRST		0x01
#define SWD_SAMD_DSU_CTRL_CE		0x10

#define SWD_SAMD_DSU_STATUSA_DONE	0x01

#endif
