// SPDX-License-Identifier: GPL-2.0
/*
 * Copyright (c) 2026 The Linux Foundation. All rights reserved.
 */
#include <linux/bits.h>
#include <linux/bitfield.h>

#ifndef __TPS25751_H__
#define __TPS25751_H__

/* events 1-4 */
#define TPS_REG_EVENT1_PD_HARD_RESET			BIT(1)
#define TPS_REG_EVENT1_PLUG_INSERT_OR_REMOVAL		BIT(3)
#define TPS_REG_EVENT1_PR_SWAP_COMPLETE			BIT(4)
#define TPS_REG_EVENT1_DR_SWAP_COMPLETE			BIT(5)
#define TPS_REG_EVENT1_NEW_CONTRACT_AS_CONS		BIT(12)
#define TPS_REG_EVENT1_NEW_CONTRACT_AS_PROV		BIT(13)
#define TPS_REG_EVENT1_SOURCE_CAP_MSG_RCVD		BIT(14)
#define TPS_REG_EVENT1_PR_SWAP_REQUESTED		BIT(17)
#define TPS_REG_EVENT1_DR_SWAP_REQUESTED		BIT(18)
#define TPS_REG_EVENT1_USB_HOST_PRESENT			BIT(20)
#define TPS_REG_EVENT1_USB_HOST_PRESENT_NO_LONGER	BIT(21)
#define TPS_REG_EVENT1_PP_SWITCH_CHANGED		BIT(23)
#define TPS_REG_EVENT1_POWER_STATUS_UPDATE		BIT(24)
#define TPS_REG_EVENT1_STATUS_UPDATE			BIT(26)
#define TPS_REG_EVENT1_PD_STATUS_UPDATE			BIT(27)
#define TPS_REG_EVENT1_CMD_COMPLETE			BIT(30)

/* events 5-8 */
#define TPS_REG_EVENT1_ERROR_DEVICE_INCOMPLETE				BIT(0)
#define TPS_REG_EVENT1_ERROR_CANNOT_PROVIDE_VOLATAGE_OR_CURRENT		BIT(1)
#define TPS_REG_EVENT1_ERROR_CAN_PROVIDE_VOLATAGE_OR_CURRENT_LATER	BIT(2)
#define TPS_REG_EVENT1_ERROR_POWER_EVENT_OCCURRED			BIT(3)
#define TPS_REG_EVENT1_ERROR_MISSING_GET_CAP_MESSAGE			BIT(4)
#define TPS_REG_EVENT1_ERROR_PROTOCOL_ERROR				BIT(6)
#define TPS_REG_EVENT1_ERROR_MESSAGAE_DATA				BIT(7)
#define TPS_REG_EVENT1_SINK_TRANSITION_COMPLETE				BIT(9)
#define TPS_REG_EVENT1_PLUG_EARLY_NOTIFICATION				BIT(10)
#define TPS_REG_EVENT1_ERROR_PLUG_EARLY_NOTIFICATION			BIT(11)
#define TPS_REG_EVENT1_ERROR_UNABLE_TO_SOURCE				BIT(14)

/* events 9-11 */
#define TPS_REG_EVENT1_TX_MEM_BUFFER_EMPTY	BIT(1)
#define TPS_REG_EVENT1_PATCH_LOADED		BIT(16)
#define TPS_REG_EVENT1_READY_FOR_PATCH		BIT(17)
#define TPS_REG_EVENT1_I2C_MASTER_NACKED	BIT(18)

/* STATUS Register */
#define TPS_REG_STATUS_PLUG_MASK		BIT(0)
#define TPS_REG_STATUS_PLUG_PRESENT(_s) \
	FIELD_GET(TPS_REG_STATUS_PLUG_MASK, _s)
#define TPS_REG_STATUS_CONN_STATE_MASK		GENMASK(3, 1)
#define TPS_REG_STATUS_CONN_STATE(_s) \
	FIELD_GET(TPS_REG_STATUS_CONN_STATE_MASK, _s)
#define TPS_REG_STATUS_PLUG_ORIENTATION_MASK	BIT(4)
#define TPS_REG_STATUS_PLUG_ORIENTATION(_s) \
	FIELD_GET(TPS_REG_STATUS_PLUG_ORIENTATION_MASK, _s)
#define TPS_REG_STATUS_PORT_ROLE_MASK		BIT(5)
#define TPS_REG_STATUS_PORT_ROLE(_s) \
	FIELD_GET(TPS_REG_STATUS_PORT_ROLE_MASK, _s)
#define TPS_REG_STATUS_DATA_ROLE_MASK		BIT(6)
#define TPS_REG_STATUS_DATA_ROLE(_s) \
	FIELD_GET(TPS_REG_STATUS_DATA_ROLE_MASK, _s)
#define TPS_REG_STATUS_VBUS_STATUS_MASK		GENMASK(21, 20)
#define TPS_REG_STATUS_VBUS_STATUS(_s) \
	FIELD_GET(TPS_REG_STATUS_VBUS_STATUS_MASK, _s)
#define TPS_REG_STATUS_USB_HOST_PRESENT_MASK	GENMASK(23, 22)
#define TPS_REG_STATUS_USB_HOST_PRESENT(_s) \
	FIELD_GET(TPS_REG_STATUS_USB_HOST_PRESENT_MASK, _s)
#define TPS_REG_STATUS_ACTING_AS_LEGACY_MASK	GENMASK(25, 24)
#define TPS_REG_STATUS_ACTING_AS_LEGACY(_s) \
	FIELD_GET(TPS_REG_STATUS_ACTING_AS_LEGACY_MASK, _s)
#define TPS_REG_STATUS_BIST_MASK		BIT(27)
#define TPS_REG_STATUS_BIST(_s) \
	FIELD_GET(TPS_REG_STATUS_BIST_MASK, _s)

/* BOOT STATUS REG */
#define TPS_REG_BOOT_STATUS_PATCH_HEADER_ERR_MASK	BIT(0)
#define TPS_REG_BOOT_STATUS_PATCH_HEADER_ERR(_s) \
	FIELD_GET(TPS_REG_BOOT_STATUS_PATCH_HEADER_ERR_MASK, _s)
#define TPS_REG_BOOT_STATUS_DEAD_BATTERY_FLAG_MASK	BIT(2)
#define TPS_REG_BOOT_STATUS_DEAD_BATTERY_FLAG(_s) \
	FIELD_GET(TPS_REG_BOOT_STATUS_DEAD_BATTERY_FLAG_MASK, _s)
#define TPS_REG_BOOT_STATUS_I2C_EEPROM_PRESENT_MASK	BIT(3)
#define TPS_REG_BOOT_STATUS_I2C_EEPROM_PRESENT(_s) \
	FIELD_GET(TPS_REG_BOOT_STATUS_I2C_EEPROM_PRESENT_MASK, _s)
#define TPS_REG_BOOT_STATUS_PATCH_DOWNLOAD_ERR_MASK	BIT(10)
#define TPS_REG_BOOT_STATUS_PATCH_DOWNLOAD_ERR(_s) \
	FIELD_GET(TPS_REG_BOOT_STATUS_PATCH_DOWNLOAD_ERR_MASK, _s)
#define TPS_REG_BOOT_STATUS_MASTER_TSD_MASK		BIT(19)
#define TPS_REG_BOOT_STATUS_MASTER_TSD(_s) \
	FIELD_GET(TPS_REG_BOOT_STATUS_MASTER_TSD_MASK, _s)
#define TPS_REG_BOOT_STATUS_PATCH_CONFIG_SOURCE_MASK	GENMASK(31, 29)
#define TPS_REG_BOOT_STATUS_PATCH_CONFIG_SOURCE(_s) \
	FIELD_GET(TPS_REG_BOOT_STATUS_PATCH_CONFIG_SOURCE_MASK, _s)
#define TPS_REG_BOOT_STATUS_REV_ID_MASK			GENMASK_ULL(39, 32)
#define TPS_REG_BOOT_STATUS_REV_ID(_s) \
	FIELD_GET(TPS_REG_BOOT_STATUS_REV_ID_MASK, _s)

/* POWER STATUS REG */
#define TPS_REG_POWER_STATUS_POWER_CONNECTION_MASK	BIT(0)
#define TPS_REG_POWER_STATUS_POWER_CONNECTION(_s) \
	FIELD_GET(TPS_REG_POWER_STATUS_POWER_CONNECTION_MASK, _s)
#define TPS_REG_POWER_STATUS_SOURCE_SINK_MASK		BIT(1)
#define TPS_REG_POWER_STATUS_SOURCE_SINK(_s) \
	FIELD_GET(TPS_REG_POWER_STATUS_SOURCE_SINK_MASK, _s)
#define TPS_REG_POWER_STATUS_TYPEC_CURRENT_MASK	GENMASK(3, 2)
#define TPS_REG_POWER_STATUS_TYPEC_CURRENT(_s) \
	FIELD_GET(TPS_REG_POWER_STATUS_TYPEC_CURRENT_MASK, _s)
#define TPS_REG_POWER_STATUS_CHARGER_DETECT_MASK	GENMASK(7, 4)
#define TPS_REG_POWER_STATUS_CHARGER_DETECT(_s) \
	FIELD_GET(TPS_REG_POWER_STATUS_CHARGER_DETECT_MASK, _s)
#define TPS_REG_POWER_STATUS_CHARGER_ADVERTISE_MASK	GENMASK(9, 8)
#define TPS_REG_POWER_STATUS_CHARGER_ADVERTISE(_s) \
	FIELD_GET(TPS_REG_POWER_STATUS_CHARGER_ADVERTISE_MASK, _s)

/* PD STATUS REG */
#define TPS_REG_PD_STATUS_CC_PULL_UP_MASK		GENMASK(3, 2)
#define TPS_REG_PD_STATUS_CC_PULL_UP(_s) \
	FIELD_GET(TPS_REG_PD_STATUS_CC_PULL_UP_MASK, _s)
#define TPS_REG_PD_STATUS_PORT_TYPE_MASK		GENMASK(5, 4)
#define TPS_REG_PD_STATUS_PORT_TYPE(_s) \
	FIELD_GET(TPS_REG_PD_STATUS_PORT_TYPE_MASK, _s)
#define TPS_REG_PD_STATUS_PERESENT_PD_ROLE_MASK		BIT(6)
#define TPS_REG_PD_STATUS_PD_CONN(_s) \
	FIELD_GET(TPS_REG_PD_STATUS_PERESENT_PD_ROLE_MASK, _s)
#define TPS_REG_PD_STATUS_SOFT_RESET_DETAILS_MASK	GENMASK(12, 8)
#define TPS_REG_PD_STATUS_SOFT_RESET_DETAILS(_s) \
	FIELD_GET(TPS_REG_PD_STATUS_SOFT_RESET_DETAILS_MASK, _s)
#define TPS_REG_PD_STATUS_HARD_RESET_DETAILS_MASK	GENMASK(21, 16)
#define TPS_REG_PD_STATUS_HARD_RESET_DETAILS(_s) \
	FIELD_GET(TPS_REG_PD_STATUS_HARD_RESET_DETAILS_MASK, _s)
#define TPS_REG_PD_STATUS_ERR_RECOVERY_DETAILS_MASK	GENMASK(27, 22)
#define TPS_REG_PD_STATUS_ERR_RECOVERY_DETAILS(_s) \
	FIELD_GET(TPS_REG_PD_STATUS_ERR_RECOVERY_DETAILS_MASK, _s)
#define TPS_REG_PD_STATUS_DATA_RESET_DETAILS_MASK	GENMASK(30, 28)
#define TPS_REG_PD_STATUS_DATA_RESET_DETAILS(_s) \
	FIELD_GET(TPS_REG_PD_STATUS_DATA_RESET_DETAILS_MASK, _s)

/* TX_SOURCE_CAPS REG */
#define TPS_PDO_NUM_VALID_PDOS_MASK	GENMASK(2, 0)
#define TPS_PDO_NUM_VALID_PDOS(_header) \
	FIELD_GET(TPS_PDO_NUM_VALID_PDOS_MASK, _header)
#define TPS_PDO_MAX_CURRENT_MASK	GENMASK(9, 0)
#define TPS_PDO_MAX_CURRENT(_pdo) \
	FIELD_GET(TPS_PDO_MAX_CURRENT_MASK, _pdo)
#define TPS_PDO_MAX_VOLTAGE_MASK	GENMASK(19, 10)
#define TPS_PDO_MAX_VOLTAGE_(_pdo) \
	FIELD_GET(TPS_PDO_MAX_VOLTAGE_MASK, _pdo)

#define TPS_PORT_TYPE_SINK_SOURCE	0
#define TPS_PORT_TYPE_SINK		1
#define TPS_PORT_TYPE_SOURCE		2
#define TPS_PORT_TYPE_SOURCE_SINK	3

#define TPS_TYPEC_CURRENT_USB_DEFAULT	0
#define TPS_TYPEC_CURRENT_1_5_A		1
#define TPS_TYPEC_CURRENT_3_0_A		2
#define TPS_TYPEC_CURRENT_PD		3

#endif /* __TPS25751_H__ */
