#
# Makefile for kernel SPI STP LAYER driver.
#

obj-$(CONFIG_SPI_STP)		+= spi_stp_driver.o
obj-$(CONFIG_SPI_STP)		+= spi_stp_dev.o
obj-$(CONFIG_SPI_STP)		+= stp.o
obj-$(CONFIG_SPI_STP)		+= stp_master.o
obj-$(CONFIG_SPI_STP)		+= stp_pipeline.o
obj-$(CONFIG_SPI_STP)		+= stp_master_io.o
obj-$(CONFIG_SPI_STP)		+= stp_ie.o
obj-$(CONFIG_SPI_STP)		+= stp_notification.o
obj-$(CONFIG_SPI_STP)		+= stp_router.o
obj-$(CONFIG_SPI_STP)		+= stp_raw_dev.o

