obj-$(CONFIG_OCULUS_SWD)		+= fwupdate_manager.o
obj-$(CONFIG_OCULUS_SWD)		+= swd.o
obj-$(CONFIG_OCULUS_SWD)		+= swd_driver.o
obj-$(CONFIG_OCULUS_SWD_HUBERT)		+= hubert_swd_ops.o
obj-$(CONFIG_OCULUS_SWD_QM35)		+= qm35xxx_swd_ops.o
obj-$(CONFIG_OCULUS_SWD_SAFETYBOSS)	+= safetyboss_swd_ops.o
obj-$(CONFIG_OCULUS_SWD_SYNCBOSS)	+= syncboss_swd_ops.o
