/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Copyright (c) 2018-2021, The Linux Foundation. All rights reserved.
 */

#ifndef __CVP_HFI_IO_H__
#define __CVP_HFI_IO_H__

#include <linux/io.h>
#ifndef HALLIDAY_DISABLE
    #define EVA_LSR
#endif
#define CVP_TOP_BASE_OFFS			0x00000000
#define CVP_SS_IDLE_STATUS		(CVP_TOP_BASE_OFFS + 0x50)

#define CVP_CPU_BASE_OFFS			0x000A0000
#define CVP_AON_BASE_OFFS			0x000E0000

#define CVP_CPU_CS_A2HSOFTINTEN		(CVP_CPU_BASE_OFFS + 0x10)
#define CVP_CPU_CS_A2HSOFTINTENCLR	(CVP_CPU_BASE_OFFS + 0x14)
#define CVP_CPU_CS_A2HSOFTINT		(CVP_CPU_BASE_OFFS + 0x18)
#define CVP_CPU_CS_A2HSOFTINTCLR	(CVP_CPU_BASE_OFFS + 0x1C)
#define CVP_CPU_CS_VMIMSG		(CVP_CPU_BASE_OFFS + 0x34)
#define CVP_CPU_CS_VMIMSGAG0		(CVP_CPU_BASE_OFFS + 0x38)
#define CVP_CPU_CS_VMIMSGAG1		(CVP_CPU_BASE_OFFS + 0x3C)
#define CVP_CPU_CS_VMIMSGAG2		(CVP_CPU_BASE_OFFS + 0x40)
#define CVP_CPU_CS_VMIMSGAG3		(CVP_CPU_BASE_OFFS + 0x44)
#define CVP_CPU_CS_SCIACMD			(CVP_CPU_BASE_OFFS + 0x48)
#define CVP_CPU_CS_AXI4_QOS		(CVP_CPU_BASE_OFFS + 0x13C)
#define CVP_CPU_CS_H2XSOFTINTEN		(CVP_CPU_BASE_OFFS + 0x148)

/* CVP_CTRL_STATUS */
#define CVP_CPU_CS_SCIACMDARG0		(CVP_CPU_BASE_OFFS + 0x4C)
#define CVP_CPU_CS_SCIACMDARG0_BMSK	0xff
#define CVP_CPU_CS_SCIACMDARG0_SHFT	0x0
#define CVP_CPU_CS_SCIACMDARG0_HFI_CTRL_ERROR_STATUS_BMSK	0xfe
#define CVP_CPU_CS_SCIACMDARG0_HFI_CTRL_ERROR_STATUS_SHFT	0x1
#define CVP_CPU_CS_SCIACMDARG0_HFI_CTRL_INIT_STATUS_BMSK	0x1
#define CVP_CPU_CS_SCIACMDARG0_HFI_CTRL_INIT_STATUS_SHFT	0x0
#define CVP_CPU_CS_SCIACMDARG0_HFI_CTRL_PC_READY           0x100

/* HFI_QTBL_INFO */
#define CVP_CPU_CS_SCIACMDARG1		(CVP_CPU_BASE_OFFS + 0x50)

/* HFI_QTBL_ADDR */
#define CVP_CPU_CS_SCIACMDARG2		(CVP_CPU_BASE_OFFS + 0x54)

/* HFI_VERSION_INFO */
#define CVP_CPU_CS_SCIACMDARG3		(CVP_CPU_BASE_OFFS + 0x58)

/* CVP_SFR_ADDR */
#define CVP_CPU_CS_SCIBCMD		(CVP_CPU_BASE_OFFS + 0x5C)

/* CVP_MMAP_ADDR */
#define CVP_CPU_CS_SCIBCMDARG0		(CVP_CPU_BASE_OFFS + 0x60)

/* CVP_UC_REGION_ADDR */
#define CVP_CPU_CS_SCIBARG1		(CVP_CPU_BASE_OFFS + 0x64)

/* CVP_UC_REGION_ADDR */
#define CVP_CPU_CS_SCIBARG2		(CVP_CPU_BASE_OFFS + 0x68)

#define CVP_CPU_CS_SCIBARG3		(CVP_CPU_BASE_OFFS + 0x6C)

#define CVP_CPU_CS_H2ASOFTINTEN		(CVP_CPU_BASE_OFFS + 0x148)
#define CVP_CPU_CS_H2ASOFTINTENCLR	(CVP_CPU_BASE_OFFS + 0x14c)
#define CVP_CPU_CS_H2ASOFTINT		(CVP_CPU_BASE_OFFS + 0x150)
#define CVP_CPU_CS_H2ASOFTINTCLR	(CVP_CPU_BASE_OFFS + 0x154)

#define CVP_AHB_BRIDGE_SYNC_RESET	(CVP_CPU_BASE_OFFS + 0x160)

/* FAL10 Feature Control */
#define CVP_CPU_CS_X2RPMh		(CVP_CPU_BASE_OFFS + 0x168)
#define CVP_CPU_CS_X2RPMh_MASK0_BMSK	0x1
#define CVP_CPU_CS_X2RPMh_MASK0_SHFT	0x0
#define CVP_CPU_CS_X2RPMh_MASK1_BMSK	0x2
#define CVP_CPU_CS_X2RPMh_MASK1_SHFT	0x1
#define CVP_CPU_CS_X2RPMh_SWOVERRIDE_BMSK	0x4
#define CVP_CPU_CS_X2RPMh_SWOVERRIDE_SHFT	0x3

/*
 * --------------------------------------------------------------------------
 * MODULE: cvp_wrapper
 * --------------------------------------------------------------------------
 */
#define CVP_WRAPPER_BASE_OFFS		0x000B0000

#define CVP_WRAPPER_HW_VERSION		(CVP_WRAPPER_BASE_OFFS + 0x00)
#define CVP_WRAPPER_HW_VERSION_MAJOR_VERSION_MASK  0x78000000
#define CVP_WRAPPER_HW_VERSION_MAJOR_VERSION_SHIFT 28
#define CVP_WRAPPER_HW_VERSION_MINOR_VERSION_MASK  0xFFF0000
#define CVP_WRAPPER_HW_VERSION_MINOR_VERSION_SHIFT 16
#define CVP_WRAPPER_HW_VERSION_STEP_VERSION_MASK   0xFFFF

#define CVP_WRAPPER_INTR_STATUS	(CVP_WRAPPER_BASE_OFFS + 0x0C)
#define CVP_WRAPPER_INTR_STATUS_A2HWD_BMSK	0x8
#define CVP_WRAPPER_INTR_STATUS_A2H_BMSK	0x4

#define CVP_SS_IRQ_MASK    (CVP_TOP_BASE_OFFS + 0x04)
#define CVP_SS_INTR_BMASK  (0x100)

#define CVP_WRAPPER_INTR_MASK		(CVP_WRAPPER_BASE_OFFS + 0x10)
#define CVP_FATAL_INTR_BMSK	(CVP_WRAPPER_INTR_MASK_CPU_NOC_BMSK | \
				CVP_WRAPPER_INTR_MASK_CORE_NOC_BMSK | \
				CVP_WRAPPER_INTR_MASK_A2HWD_BMSK)
#define CVP_WRAPPER_INTR_MASK_CPU_NOC_BMSK	0x40
#define CVP_WRAPPER_INTR_MASK_CORE_NOC_BMSK	0x20
#define CVP_WRAPPER_INTR_MASK_A2HWD_BMSK	0x8
#define CVP_WRAPPER_INTR_MASK_A2HCPU_BMSK	0x4
#define CVP_WRAPPER_INTR_MASK_A2HCPU_SHFT	0x2

#define CVP_WRAPPER_INTR_CLEAR		(CVP_WRAPPER_BASE_OFFS + 0x14)

#define CVP_WRAPPER_TZ_BASE_OFFS		0x000C0000

#define CVP_WRAPPER_INTR_CLEAR_A2HWD_BMSK	0x10
#define CVP_WRAPPER_INTR_CLEAR_A2HWD_SHFT	0x4
#define CVP_WRAPPER_INTR_CLEAR_A2H_BMSK	0x4
#define CVP_WRAPPER_INTR_CLEAR_A2H_SHFT	0x2
#define CVP_WRAPPER_CPU_STATUS		(CVP_WRAPPER_TZ_BASE_OFFS + 0x10)
#define CVP_WRAPPER_AXI_CLOCK_CONFIG	(CVP_WRAPPER_TZ_BASE_OFFS + 0x14)
#define CVP_WRAPPER_QNS4PDXFIFO_RESET	(CVP_WRAPPER_TZ_BASE_OFFS + 0x18)
#define CVP_WRAPPER_CPU_CGC_DIS	(CVP_WRAPPER_BASE_OFFS + 0x2010)

#define CVP_WRAPPER_CPU_CLOCK_CONFIG	(CVP_WRAPPER_BASE_OFFS + 0x50)
#define CVP_WRAPPER_DEBUG_BRIDGE_LPI_CONTROL	(CVP_WRAPPER_BASE_OFFS + 0x54)
#define CVP_WRAPPER_DEBUG_BRIDGE_LPI_STATUS	(CVP_WRAPPER_BASE_OFFS + 0x58)
#define CVP_WRAPPER_CPU_NOC_LPI_CONTROL		(CVP_WRAPPER_BASE_OFFS + 0x5C)
#define CVP_WRAPPER_CPU_NOC_LPI_STATUS		(CVP_WRAPPER_BASE_OFFS + 0x60)
#define CVP_WRAPPER_CORE_CLOCK_CONFIG		(CVP_WRAPPER_BASE_OFFS + 0x88)
//Aurora
#define CVP_WRAPPER_CORE_SW_RESET_TRIGGER		(CVP_WRAPPER_BASE_OFFS + 0x94)
#define CVP_WRAPPER_CORE_SW_RESET_H		(CVP_WRAPPER_BASE_OFFS + 0x98)
#define CVP_WRAPPER_CORE_SW_RESET_L		(CVP_WRAPPER_BASE_OFFS + 0x9C)
#define CVP_WRAPPER_CORE_SW_RESET_REQ_ACK	(CVP_WRAPPER_BASE_OFFS + 0xA0)




#define CVP_CTRL_INIT		CVP_CPU_CS_SCIACMD

#define CVP_CTRL_STATUS	CVP_CPU_CS_SCIACMDARG0
#define CVP_CTRL_INIT_STATUS__M \
		CVP_CPU_CS_SCIACMDARG0_HFI_CTRL_INIT_STATUS_BMSK
#define CVP_CTRL_ERROR_STATUS__M \
		CVP_CPU_CS_SCIACMDARG0_HFI_CTRL_ERROR_STATUS_BMSK
#define CVP_CTRL_INIT_IDLE_MSG_BMSK \
		CVP_CPU_CS_SCIACMDARG0_HFI_CTRL_INIT_IDLE_MSG_BMSK
#define CVP_CTRL_STATUS_PC_READY \
		CVP_CPU_CS_SCIACMDARG0_HFI_CTRL_PC_READY


#define CVP_QTBL_INFO		CVP_CPU_CS_SCIACMDARG1

#define CVP_QTBL_ADDR		CVP_CPU_CS_SCIACMDARG2

#define CVP_VERSION_INFO	CVP_CPU_CS_SCIACMDARG3

#define CVP_SFR_ADDR		CVP_CPU_CS_SCIBCMD
#define CVP_MMAP_ADDR		CVP_CPU_CS_SCIBCMDARG0
#define CVP_UC_REGION_ADDR	CVP_CPU_CS_SCIBARG1
#define CVP_UC_REGION_SIZE	CVP_CPU_CS_SCIBARG2

/* HFI_DSP_QTBL_ADDR
 * 31:3 - HFI_DSP_QTBL_ADDR
 *        4-byte aligned Address
 */
#define HFI_DSP_QTBL_ADDR	CVP_CPU_CS_VMIMSG

/* HFI_DSP_UC_REGION_ADDR
 * 31:20 - HFI_DSP_UC_REGION_ADDR
 *         1MB aligned address.
 *         Uncached Region start Address. This region covers
 *         HFI DSP QTable,
 *         HFI DSP Queue Headers,
 *         HFI DSP Queues,
 */
#define HFI_DSP_UC_REGION_ADDR	CVP_CPU_CS_VMIMSGAG0

/* HFI_DSP_UC_REGION_SIZE
 * 31:20 - HFI_DSP_UC_REGION_SIZE
 *         Multiples of 1MB.
 *         Size of the DSP_UC_REGION Uncached Region
 */
#define HFI_DSP_UC_REGION_SIZE	CVP_CPU_CS_VMIMSGAG1

/*
 * --------------------------------------------------------------------------
 * MODULE: vcodec noc error log registers
 * --------------------------------------------------------------------------
 */
#define CVP_NOC_BASE_OFFS		0x000D0000
#define CVP_NOC_ERR_SWID_LOW_OFFS	(CVP_NOC_BASE_OFFS + 0x0)
#define CVP_NOC_ERR_SWID_HIGH_OFFS	(CVP_NOC_BASE_OFFS + 0x4)
#define CVP_NOC_ERR_MAINCTL_LOW_OFFS	(CVP_NOC_BASE_OFFS + 0x8)
#define CVP_NOC_ERR_ERRVLD_LOW_OFFS	(CVP_NOC_BASE_OFFS + 0x10)
#define CVP_NOC_ERR_ERRCLR_LOW_OFFS	(CVP_NOC_BASE_OFFS + 0x18)
#define CVP_NOC_ERR_ERRLOG0_LOW_OFFS	(CVP_NOC_BASE_OFFS + 0x20)
#define CVP_NOC_ERR_ERRLOG0_HIGH_OFFS	(CVP_NOC_BASE_OFFS + 0x24)
#define CVP_NOC_ERR_ERRLOG1_LOW_OFFS	(CVP_NOC_BASE_OFFS + 0x28)
#define CVP_NOC_ERR_ERRLOG1_HIGH_OFFS	(CVP_NOC_BASE_OFFS + 0x2C)
#define CVP_NOC_ERR_ERRLOG2_LOW_OFFS	(CVP_NOC_BASE_OFFS + 0x30)
#define CVP_NOC_ERR_ERRLOG2_HIGH_OFFS	(CVP_NOC_BASE_OFFS + 0x34)
#define CVP_NOC_ERR_ERRLOG3_LOW_OFFS	(CVP_NOC_BASE_OFFS + 0x38)
#define CVP_NOC_ERR_ERRLOG3_HIGH_OFFS	(CVP_NOC_BASE_OFFS + 0x3C)
#define CVP_NOC_SBM_SENSELN0_LOW	(CVP_NOC_BASE_OFFS + 0x300)
#define CVP_NOC_CPU_PENDING_MASK	0x3F80000

#define CVP_NOC_CORE_BASE_OFFS			0x00010000
#define CVP_NOC_MAIN_SIDEBANDMANAGER_SENSELN0_LOW \
		(CVP_NOC_CORE_BASE_OFFS + 0x300)
#define CVP_NOC_MAIN_SIDEBANDMANAGER_SENSELN0_HIGH \
		(CVP_NOC_CORE_BASE_OFFS + 0x304)
#define CVP_NOC_MAIN_SIDEBANDMANAGER_SENSELN1_HIGH \
		(CVP_NOC_CORE_BASE_OFFS + 0x30C)
#define CVP_NOC_CORE_ERR_SWID_LOW_OFFS \
		(CVP_NOC_CORE_BASE_OFFS + 0x0)
#define CVP_NOC_CORE_ERR_SWID_HIGH_OFFS \
		(CVP_NOC_CORE_BASE_OFFS + 0x4)
#define CVP_NOC_CORE_ERR_MAINCTL_LOW_OFFS \
		(CVP_NOC_CORE_BASE_OFFS + 0x8)
#define CVP_NOC_CORE_ERR_ERRVLD_LOW_OFFS \
		(CVP_NOC_CORE_BASE_OFFS + 0x10)
#define CVP_NOC_CORE_ERR_ERRCLR_LOW_OFFS \
		(CVP_NOC_CORE_BASE_OFFS + 0x18)
#define CVP_NOC_CORE_ERR_ERRLOG0_LOW_OFFS \
		(CVP_NOC_CORE_BASE_OFFS + 0x20)
#define CVP_NOC_CORE_ERR_ERRLOG0_HIGH_OFFS \
		(CVP_NOC_CORE_BASE_OFFS + 0x24)
#define CVP_NOC_CORE_ERR_ERRLOG1_LOW_OFFS \
		(CVP_NOC_CORE_BASE_OFFS + 0x28)
#define CVP_NOC_CORE_ERR_ERRLOG1_HIGH_OFFS \
		(CVP_NOC_CORE_BASE_OFFS + 0x2C)
#define CVP_NOC_CORE_ERR_ERRLOG2_LOW_OFFS \
		(CVP_NOC_CORE_BASE_OFFS + 0x30)
#define CVP_NOC_CORE_ERR_ERRLOG2_HIGH_OFFS \
		(CVP_NOC_CORE_BASE_OFFS + 0x34)
#define CVP_NOC_CORE_ERR_ERRLOG3_LOW_OFFS \
		(CVP_NOC_CORE_BASE_OFFS + 0x38)
#define CVP_NOC_CORE_ERR_ERRLOG3_HIGH_OFFS \
		(CVP_NOC_CORE_BASE_OFFS + 0x3C)
#define CVP_NOC_PRIORITYLUT_LOW \
		(CVP_NOC_CORE_BASE_OFFS + 0x3030)
#define CVP_NOC_PRIORITYLUT_HIGH \
		(CVP_NOC_CORE_BASE_OFFS + 0x3034)
#define CVP_NOC_URGENCY_LOW \
		(CVP_NOC_CORE_BASE_OFFS + 0x3038)
#define CVP_NOC_DANGERLUT_LOW \
		(CVP_NOC_CORE_BASE_OFFS + 0x3040)
#define CVP_NOC_SAFELUT_LOW \
		(CVP_NOC_CORE_BASE_OFFS + 0x3048)
#define CVP_NOC_RESET_REQ \
		(CVP_NOC_CORE_BASE_OFFS + 0xf000)
#define CVP_NOC_RESET_ACK \
		(CVP_NOC_CORE_BASE_OFFS + 0xf004)

//below macros are updated from ARM_ADDRESS_FILE.h from EVA FW.
#define   AON_WRAPPER_CVP_NOC_RESET_REQ___POR    0x00000000
#define   AON_WRAPPER_CVP_NOC_RESET_REQ__AMM_B0_5_ACK_SEL___POR 0x0
#define   AON_WRAPPER_CVP_NOC_RESET_REQ__AMM_B0_4_ACK_SEL___POR 0x0
#define   AON_WRAPPER_CVP_NOC_RESET_REQ__AMM_B0_3_ACK_SEL___POR 0x0
#define   AON_WRAPPER_CVP_NOC_RESET_REQ__AMM_B0_5___POR 0x0
#define   AON_WRAPPER_CVP_NOC_RESET_REQ__AMM_B0_4___POR 0x0
#define   AON_WRAPPER_CVP_NOC_RESET_REQ__AMM_B0_3___POR 0x0
#define   AON_WRAPPER_CVP_NOC_RESET_REQ__AMM_B0_2___POR 0x0
#define   AON_WRAPPER_CVP_NOC_RESET_REQ__AMM_B0_1___POR 0x0
#define   AON_WRAPPER_CVP_NOC_RESET_REQ__AMM_B0_0___POR 0x0
#define   AON_WRAPPER_CVP_NOC_RESET_REQ__AMM_B0_5_ACK_SEL___M 0x00000100
#define   AON_WRAPPER_CVP_NOC_RESET_REQ__AMM_B0_5_ACK_SEL___S               8
#define   AON_WRAPPER_CVP_NOC_RESET_REQ__AMM_B0_4_ACK_SEL___M 0x00000080
#define   AON_WRAPPER_CVP_NOC_RESET_REQ__AMM_B0_4_ACK_SEL___S               7
#define   AON_WRAPPER_CVP_NOC_RESET_REQ__AMM_B0_3_ACK_SEL___M 0x00000040
#define   AON_WRAPPER_CVP_NOC_RESET_REQ__AMM_B0_3_ACK_SEL___S               6
#define   AON_WRAPPER_CVP_NOC_RESET_REQ__AMM_B0_5___M 0x00000020
#define   AON_WRAPPER_CVP_NOC_RESET_REQ__AMM_B0_5___S               5
#define   AON_WRAPPER_CVP_NOC_RESET_REQ__AMM_B0_4___M 0x00000010
#define   AON_WRAPPER_CVP_NOC_RESET_REQ__AMM_B0_4___S               4
#define   AON_WRAPPER_CVP_NOC_RESET_REQ__AMM_B0_3___M 0x00000008
#define   AON_WRAPPER_CVP_NOC_RESET_REQ__AMM_B0_3___S               3
#define   AON_WRAPPER_CVP_NOC_RESET_REQ__AMM_B0_2___M 0x00000004
#define   AON_WRAPPER_CVP_NOC_RESET_REQ__AMM_B0_2___S               2
#define   AON_WRAPPER_CVP_NOC_RESET_REQ__AMM_B0_1___M 0x00000002
#define   AON_WRAPPER_CVP_NOC_RESET_REQ__AMM_B0_1___S               1
#define   AON_WRAPPER_CVP_NOC_RESET_REQ__AMM_B0_0___M 0x00000001
#define   AON_WRAPPER_CVP_NOC_RESET_REQ__AMM_B0_0___S               0
#define   AON_WRAPPER_CVP_NOC_RESET_REQ___M      0x000001FF
#define   AON_WRAPPER_CVP_NOC_RESET_REQ___S                    0

#define   AON_WRAPPER_CVP_NOC_RESET_ACK___POR    0x00000000
#define   AON_WRAPPER_CVP_NOC_RESET_ACK__AMM_B0_5___POR 0x0
#define   AON_WRAPPER_CVP_NOC_RESET_ACK__AMM_B0_4___POR 0x0
#define   AON_WRAPPER_CVP_NOC_RESET_ACK__AMM_B0_3___POR 0x0
#define   AON_WRAPPER_CVP_NOC_RESET_ACK__AMM_B0_2___POR 0x0
#define   AON_WRAPPER_CVP_NOC_RESET_ACK__AMM_B0_1___POR 0x0
#define   AON_WRAPPER_CVP_NOC_RESET_ACK__AMM_B0_0___POR 0x0
#define   AON_WRAPPER_CVP_NOC_RESET_ACK__AMM_B0_5___M 0x00000020
#define   AON_WRAPPER_CVP_NOC_RESET_ACK__AMM_B0_5___S               5
#define   AON_WRAPPER_CVP_NOC_RESET_ACK__AMM_B0_4___M 0x00000010
#define   AON_WRAPPER_CVP_NOC_RESET_ACK__AMM_B0_4___S               4
#define   AON_WRAPPER_CVP_NOC_RESET_ACK__AMM_B0_3___M 0x00000008
#define   AON_WRAPPER_CVP_NOC_RESET_ACK__AMM_B0_3___S               3
#define   AON_WRAPPER_CVP_NOC_RESET_ACK__AMM_B0_2___M 0x00000004
#define   AON_WRAPPER_CVP_NOC_RESET_ACK__AMM_B0_2___S               2
#define   AON_WRAPPER_CVP_NOC_RESET_ACK__AMM_B0_1___M 0x00000002
#define   AON_WRAPPER_CVP_NOC_RESET_ACK__AMM_B0_1___S               1
#define   AON_WRAPPER_CVP_NOC_RESET_ACK__AMM_B0_0___M 0x00000001
#define   AON_WRAPPER_CVP_NOC_RESET_ACK__AMM_B0_0___S               0
#define   AON_WRAPPER_CVP_NOC_RESET_ACK___M      0x0000003F
#define   AON_WRAPPER_CVP_NOC_RESET_ACK___S                    0

#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H___POR  0x00000000
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_VNOC_5_PARTIAL___POR 0x0
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_VNOC_4_PARTIAL___POR 0x0
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_VNOC_3_PARTIAL___POR 0x0
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_VNOC_2_PARTIAL___POR 0x0
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_VNOC_1_PARTIAL___POR 0x0
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_VNOC_0_PARTIAL___POR 0x0
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_MPU___POR 0x0
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_MPU_RIF___POR 0x0
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_OD___POR 0x0
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_OD_RIF___POR 0x0
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_FDU___POR 0x0
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_FDU_RIF___POR 0x0
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_VPP_GCE_TOP_RIF___POR 0x0
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_VPP_GCE_TOP___POR 0x0
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_GCE_CORE_RIF___POR 0x0
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_GCE_CORE___POR 0x0
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_BIU_WR_RIF___POR 0x0
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_BIU_WR___POR 0x0
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_BIU_RD_RIF___POR 0x0
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_BIU_RD___POR 0x0
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_DMA_OTHERS___POR 0x0
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_DMA_MPU___POR 0x0
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_DMA_OD___POR 0x0
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_DMA_VPSS_FDU___POR 0x0
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_DMA_VPP___POR 0x0
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_DMA_RIF___POR 0x0
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_DMA_NOC___POR 0x0
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_TOP_OTHERS___POR 0x0
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_TOP_RIF___POR 0x0
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_VNOC_5_PARTIAL___M 0x10000000
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_VNOC_5_PARTIAL___S              28
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_VNOC_4_PARTIAL___M 0x08000000
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_VNOC_4_PARTIAL___S              27
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_VNOC_3_PARTIAL___M 0x04000000
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_VNOC_3_PARTIAL___S              26
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_VNOC_2_PARTIAL___M 0x02000000
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_VNOC_2_PARTIAL___S              25
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_VNOC_1_PARTIAL___M 0x01000000
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_VNOC_1_PARTIAL___S              24
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_VNOC_0_PARTIAL___M 0x00800000
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_VNOC_0_PARTIAL___S              23
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_MPU___M 0x00400000
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_MPU___S              22
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_MPU_RIF___M 0x00200000
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_MPU_RIF___S              21
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_OD___M 0x00100000
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_OD___S              20
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_OD_RIF___M 0x00080000
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_OD_RIF___S              19
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_FDU___M 0x00040000
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_FDU___S              18
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_FDU_RIF___M 0x00020000
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_FDU_RIF___S              17
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_VPP_GCE_TOP_RIF___M 0x00010000
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_VPP_GCE_TOP_RIF___S              16
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_VPP_GCE_TOP___M 0x00008000
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_VPP_GCE_TOP___S              15
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_GCE_CORE_RIF___M 0x00004000
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_GCE_CORE_RIF___S              14
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_GCE_CORE___M 0x00002000
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_GCE_CORE___S              13
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_BIU_WR_RIF___M 0x00001000
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_BIU_WR_RIF___S              12
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_BIU_WR___M 0x00000800
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_BIU_WR___S              11
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_BIU_RD_RIF___M 0x00000400
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_BIU_RD_RIF___S              10
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_BIU_RD___M 0x00000200
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_BIU_RD___S               9
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_DMA_OTHERS___M 0x00000100
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_DMA_OTHERS___S               8
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_DMA_MPU___M 0x00000080
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_DMA_MPU___S               7
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_DMA_OD___M 0x00000040
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_DMA_OD___S               6
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_DMA_VPSS_FDU___M 0x00000020
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_DMA_VPSS_FDU___S               5
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_DMA_VPP___M 0x00000010
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_DMA_VPP___S               4
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_DMA_RIF___M 0x00000008
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_DMA_RIF___S               3
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_DMA_NOC___M 0x00000004
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_DMA_NOC___S               2
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_TOP_OTHERS___M 0x00000002
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_TOP_OTHERS___S               1
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_TOP_RIF___M 0x00000001
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H__ARES_TOP_RIF___S               0
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H___M    0x1FFFFFFF
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_H___S                  0

#define   CVP_VPU_WRAPPER_CORE_SW_RESET_L___POR  0x00000000
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_L__ARES_ARP_TH3___POR 0x0
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_L__ARES_ARP_TH2___POR 0x0
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_L__ARES_ARP_TH1___POR 0x0
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_L__ARES_ARP_TH0___POR 0x0
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_L__ARES_GCX_R_RD_PARTIAL___POR 0x0
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_L__ARES_GCX_L_RD_PARTIAL___POR 0x0
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_L__ARES_GCX_R_WR_PARTIAL___POR 0x0
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_L__ARES_GCX_L_WR_PARTIAL___POR 0x0
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_L__ARES_DDL_GCX_R_RD_PARTIAL___POR 0x0
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_L__ARES_DDL_GCX_L_RD_PARTIAL___POR 0x0
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_L__ARES_DDL_CSC_R_WR_PARTIAL___POR 0x0
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_L__ARES_DDL_CSC_L_WR_PARTIAL___POR 0x0
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_L__ARES_CSC_R_RD_PARTIAL___POR 0x0
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_L__ARES_CSC_L_RD_PARTIAL___POR 0x0
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_L__ARES_CDM_R_RD_PARTIAL___POR 0x0
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_L__ARES_CDM_L_RD_PARTIAL___POR 0x0
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_L__ARES_DMA_ARP_TH3___POR 0x0
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_L__ARES_DMA_ARP_TH2___POR 0x0
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_L__ARES_DMA_ARP_TH1___POR 0x0
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_L__ARES_DMA_ARP_TH0___POR 0x0
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_L__ARES_ARP_TH3___M 0x10000000
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_L__ARES_ARP_TH3___S              28
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_L__ARES_ARP_TH2___M 0x08000000
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_L__ARES_ARP_TH2___S              27
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_L__ARES_ARP_TH1___M 0x04000000
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_L__ARES_ARP_TH1___S              26
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_L__ARES_ARP_TH0___M 0x02000000
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_L__ARES_ARP_TH0___S              25
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_L__ARES_GCX_R_RD_PARTIAL___M 0x00040000
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_L__ARES_GCX_R_RD_PARTIAL___S              18
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_L__ARES_GCX_L_RD_PARTIAL___M 0x00020000
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_L__ARES_GCX_L_RD_PARTIAL___S              17
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_L__ARES_GCX_R_WR_PARTIAL___M 0x00010000
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_L__ARES_GCX_R_WR_PARTIAL___S              16
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_L__ARES_GCX_L_WR_PARTIAL___M 0x00008000
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_L__ARES_GCX_L_WR_PARTIAL___S              15
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_L__ARES_DDL_GCX_R_RD_PARTIAL___M 0x00004000
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_L__ARES_DDL_GCX_R_RD_PARTIAL___S              14
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_L__ARES_DDL_GCX_L_RD_PARTIAL___M 0x00002000
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_L__ARES_DDL_GCX_L_RD_PARTIAL___S              13
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_L__ARES_DDL_CSC_R_WR_PARTIAL___M 0x00001000
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_L__ARES_DDL_CSC_R_WR_PARTIAL___S              12
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_L__ARES_DDL_CSC_L_WR_PARTIAL___M 0x00000800
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_L__ARES_DDL_CSC_L_WR_PARTIAL___S              11
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_L__ARES_CSC_R_RD_PARTIAL___M 0x00000400
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_L__ARES_CSC_R_RD_PARTIAL___S              10
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_L__ARES_CSC_L_RD_PARTIAL___M 0x00000200
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_L__ARES_CSC_L_RD_PARTIAL___S               9
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_L__ARES_CDM_R_RD_PARTIAL___M 0x00000100
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_L__ARES_CDM_R_RD_PARTIAL___S               8
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_L__ARES_CDM_L_RD_PARTIAL___M 0x00000080
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_L__ARES_CDM_L_RD_PARTIAL___S               7
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_L__ARES_DMA_ARP_TH3___M 0x00000040
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_L__ARES_DMA_ARP_TH3___S               6
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_L__ARES_DMA_ARP_TH2___M 0x00000020
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_L__ARES_DMA_ARP_TH2___S               5
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_L__ARES_DMA_ARP_TH1___M 0x00000010
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_L__ARES_DMA_ARP_TH1___S               4
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_L__ARES_DMA_ARP_TH0___M 0x00000008
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_L__ARES_DMA_ARP_TH0___S               3
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_L___M    0x1E07FFF8
#define   CVP_VPU_WRAPPER_CORE_SW_RESET_L___S                  3

#define   CVP_VPU_CPU_CS_AHB_BRIDGE_SYNC_RESET___POR 0x00000000
#define   CVP_VPU_CPU_CS_AHB_BRIDGE_SYNC_RESET__CORE_BDG_HW_RESET_DISABLE___POR 0x0
#define   CVP_VPU_CPU_CS_AHB_BRIDGE_SYNC_RESET__CORE_BDG_SW_RESET___POR 0x0
#define   CVP_VPU_CPU_CS_AHB_BRIDGE_SYNC_RESET__CORE_BDG_HW_RESET_DISABLE___M 0x00000002
#define   CVP_VPU_CPU_CS_AHB_BRIDGE_SYNC_RESET__CORE_BDG_HW_RESET_DISABLE___S               1
#define   CVP_VPU_CPU_CS_AHB_BRIDGE_SYNC_RESET__CORE_BDG_SW_RESET___M 0x00000001
#define   CVP_VPU_CPU_CS_AHB_BRIDGE_SYNC_RESET__CORE_BDG_SW_RESET___S               0
#define   CVP_VPU_CPU_CS_AHB_BRIDGE_SYNC_RESET___M 0x00000003
#define   CVP_VPU_CPU_CS_AHB_BRIDGE_SYNC_RESET___S               0

#define   CVP_SS_IDLE_STATUS___POR               0x0000C667
#define   CVP_SS_IDLE_STATUS__ARP_THREAD_3_IDLE___POR 0x0
#define   CVP_SS_IDLE_STATUS__ARP_THREAD_2_IDLE___POR 0x0
#define   CVP_SS_IDLE_STATUS__ARP_THREAD_1_IDLE___POR 0x0
#define   CVP_SS_IDLE_STATUS__ARP_THREAD_0_IDLE___POR 0x0
#define   CVP_SS_IDLE_STATUS__DMA_THREAD_3_IDLE___POR 0x0
#define   CVP_SS_IDLE_STATUS__DMA_THREAD_2_IDLE___POR 0x0
#define   CVP_SS_IDLE_STATUS__DMA_THREAD_1_IDLE___POR 0x0
#define   CVP_SS_IDLE_STATUS__DMA_THREAD_0_IDLE___POR 0x0
#define   CVP_SS_IDLE_STATUS__DMA_NOC_IDLE___POR 0x0
#define   CVP_SS_IDLE_STATUS__DMA_UBWCE_IDLE___POR 0x0
#define   CVP_SS_IDLE_STATUS__DMA_UBWCD_IDLE___POR 0x0
#define   CVP_SS_IDLE_STATUS__OD_IDLE___POR      0x1
#define   CVP_SS_IDLE_STATUS__MPU_IDLE___POR     0x1
#define   CVP_SS_IDLE_STATUS__FDU_IDLE___POR     0x1
#define   CVP_SS_IDLE_STATUS__DMA_VPP_IDLE___POR 0x1
#define   CVP_SS_IDLE_STATUS__DMA_OD_IDLE___POR  0x1
#define   CVP_SS_IDLE_STATUS__DMA_MPU_IDLE___POR 0x1
#define   CVP_SS_IDLE_STATUS__DMA_FDU_IDLE___POR 0x1
#define   CVP_SS_IDLE_STATUS__DMA_DM_IDLE___POR  0x1
#define   CVP_SS_IDLE_STATUS__DMA_LAT_IDLE___POR 0x1
#define   CVP_SS_IDLE_STATUS__ARP_THREAD_3_IDLE___M 0x40000000
#define   CVP_SS_IDLE_STATUS__ARP_THREAD_3_IDLE___S              30
#define   CVP_SS_IDLE_STATUS__ARP_THREAD_2_IDLE___M 0x20000000
#define   CVP_SS_IDLE_STATUS__ARP_THREAD_2_IDLE___S              29
#define   CVP_SS_IDLE_STATUS__ARP_THREAD_1_IDLE___M 0x10000000
#define   CVP_SS_IDLE_STATUS__ARP_THREAD_1_IDLE___S              28
#define   CVP_SS_IDLE_STATUS__ARP_THREAD_0_IDLE___M 0x08000000
#define   CVP_SS_IDLE_STATUS__ARP_THREAD_0_IDLE___S              27
#define   CVP_SS_IDLE_STATUS__DMA_THREAD_3_IDLE___M 0x04000000
#define   CVP_SS_IDLE_STATUS__DMA_THREAD_3_IDLE___S              26
#define   CVP_SS_IDLE_STATUS__DMA_THREAD_2_IDLE___M 0x02000000
#define   CVP_SS_IDLE_STATUS__DMA_THREAD_2_IDLE___S              25
#define   CVP_SS_IDLE_STATUS__DMA_THREAD_1_IDLE___M 0x01000000
#define   CVP_SS_IDLE_STATUS__DMA_THREAD_1_IDLE___S              24
#define   CVP_SS_IDLE_STATUS__DMA_THREAD_0_IDLE___M 0x00800000
#define   CVP_SS_IDLE_STATUS__DMA_THREAD_0_IDLE___S              23
#define   CVP_SS_IDLE_STATUS__DMA_NOC_IDLE___M   0x00400000
#define   CVP_SS_IDLE_STATUS__DMA_NOC_IDLE___S                22
#define   CVP_SS_IDLE_STATUS__DMA_UBWCE_IDLE___M 0x00200000
#define   CVP_SS_IDLE_STATUS__DMA_UBWCE_IDLE___S              21
#define   CVP_SS_IDLE_STATUS__DMA_UBWCD_IDLE___M 0x00100000
#define   CVP_SS_IDLE_STATUS__DMA_UBWCD_IDLE___S              20
#define   CVP_SS_IDLE_STATUS__OD_IDLE___M        0x00008000
#define   CVP_SS_IDLE_STATUS__OD_IDLE___S                     15
#define   CVP_SS_IDLE_STATUS__MPU_IDLE___M       0x00004000
#define   CVP_SS_IDLE_STATUS__MPU_IDLE___S                    14
#define   CVP_SS_IDLE_STATUS__FDU_IDLE___M       0x00000400
#define   CVP_SS_IDLE_STATUS__FDU_IDLE___S                    10
#define   CVP_SS_IDLE_STATUS__DMA_VPP_IDLE___M   0x00000200
#define   CVP_SS_IDLE_STATUS__DMA_VPP_IDLE___S                 9
#define   CVP_SS_IDLE_STATUS__DMA_OD_IDLE___M    0x00000040
#define   CVP_SS_IDLE_STATUS__DMA_OD_IDLE___S                  6
#define   CVP_SS_IDLE_STATUS__DMA_MPU_IDLE___M   0x00000020
#define   CVP_SS_IDLE_STATUS__DMA_MPU_IDLE___S                 5
#define   CVP_SS_IDLE_STATUS__DMA_FDU_IDLE___M   0x00000004
#define   CVP_SS_IDLE_STATUS__DMA_FDU_IDLE___S                 2
#define   CVP_SS_IDLE_STATUS__DMA_DM_IDLE___M    0x00000002
#define   CVP_SS_IDLE_STATUS__DMA_DM_IDLE___S                  1
#define   CVP_SS_IDLE_STATUS__DMA_LAT_IDLE___M   0x00000001
#define   CVP_SS_IDLE_STATUS__DMA_LAT_IDLE___S                 0
#define   CVP_SS_IDLE_STATUS___M                 0x7FF0C667
#define   CVP_SS_IDLE_STATUS___S                               0
//end of macros which are reference ARM_ADDRESS_FILE.h

#define CVP_AON_WRAPPER_CVP_NOC_LPI_CONTROL	(CVP_AON_BASE_OFFS + 0x8)
#define CVP_AON_WRAPPER_CVP_NOC_LPI_STATUS	(CVP_AON_BASE_OFFS + 0xC)
#ifdef EVA_LSR//LSR regs
#define CVP_AON_WRAPPER_LSR_NOC_LPI_CONTROL	(CVP_AON_BASE_OFFS + 0x10)
#define CVP_AON_WRAPPER_LSR_NOC_LPI_STATUS	(CVP_AON_BASE_OFFS + 0x14)
#endif
#define CVP_CC_BASE_OFFS			0x000F8000
#define CVP_CC_MVS1C_GDSCR			(CVP_CC_BASE_OFFS + 0x74)
#define CVP_CC_MVS1C_CBCR			(CVP_CC_BASE_OFFS + 0x8C)
#define CVP_CC_MVS1_GDSCR			(CVP_CC_BASE_OFFS + 0xC0)
#define CVP_CC_MVS1_CBCR			(CVP_CC_BASE_OFFS + 0xD4)

#ifdef EVA_LSR//LSR regs
/*
 * --------------------------------------------------------------------------
 * MODULE: LSR Video C NOC registers
 * --------------------------------------------------------------------------
 */
#define LSR_NOC_VIDEO_C_NOC         0x00030000

#define LSR_NOC_CSC_GCX_L_PRIORITYLUT_LOW \
		(LSR_NOC_VIDEO_C_NOC + 0x4030)
#define LSR_NOC_CSC_GCX_L_PRIORITYLUT_HIGH \
		(LSR_NOC_VIDEO_C_NOC + 0x4034)
#define LSR_NOC_CSC_GCX_L_URGENCY_LOW \
       (LSR_NOC_VIDEO_C_NOC + 0x4038)
#define LSR_NOC_CSC_GCX_L_DANGERLUT_LOW \
       (LSR_NOC_VIDEO_C_NOC + 0x4040)
#define LSR_NOC_CSC_GCX_L_SAFELUT_LOW \
       (LSR_NOC_VIDEO_C_NOC + 0x4048)
#define LSR_NOC_CSC_GCX_R_PRIORITYLUT_LOW \
       (LSR_NOC_VIDEO_C_NOC + 0x4430)
#define LSR_NOC_CSC_GCX_R_PRIORITYLUT_HIGH \
       (LSR_NOC_VIDEO_C_NOC + 0x4434)
#define LSR_NOC_CSC_GCX_R_URGENCY_LOW \
       (LSR_NOC_VIDEO_C_NOC + 0x4438)
#define LSR_NOC_CSC_GCX_R_DANGERLUT_LOW \
       (LSR_NOC_VIDEO_C_NOC + 0x4440)
#define LSR_NOC_CSC_GCX_R_SAFELUT_LOW \
       (LSR_NOC_VIDEO_C_NOC + 0x4448)
#define LSR_NOC_DDL_L_PRIORITYLUT_LOW \
       (LSR_NOC_VIDEO_C_NOC + 0x4830)
#define LSR_NOC_DDL_L_PRIORITYLUT_HIGH \
       (LSR_NOC_VIDEO_C_NOC + 0x4834)
#define LSR_NOC_DDL_L_URGENCY_LOW \
       (LSR_NOC_VIDEO_C_NOC + 0x4838)
#define LSR_NOC_DDL_L_DANGERLUT_LOW \
       (LSR_NOC_VIDEO_C_NOC + 0x4840)
#define LSR_NOC_DDL_L_SAFELUT_LOW \
       (LSR_NOC_VIDEO_C_NOC + 0x4848)
#define LSR_NOC_DDL_R_PRIORITYLUT_LOW \
       (LSR_NOC_VIDEO_C_NOC + 0x4C30)
#define LSR_NOC_DDL_R_PRIORITYLUT_HIGH \
       (LSR_NOC_VIDEO_C_NOC + 0x4C34)
#define LSR_NOC_DDL_R_URGENCY_LOW \
       (LSR_NOC_VIDEO_C_NOC + 0x4C38)
#define LSR_NOC_DDL_R_DANGERLUT_LOW \
       (LSR_NOC_VIDEO_C_NOC + 0x4C40)
#define LSR_NOC_DDL_R_SAFELUT_LOW \
       (LSR_NOC_VIDEO_C_NOC + 0x4C48)

/*AON_LSR_NOC_RESET_REGISTERS*/
#define AON_LSR_NOC_RESET 0x0003F000

#define AON_WRAPPER_LSR_NOC_RESET_REQ \
       (AON_LSR_NOC_RESET + 0x0)
#define AON_WRAPPER_LSR_NOC_RESET_ACK \
       (AON_LSR_NOC_RESET + 0x4)

#endif
#define CVP_CORE_POWER_STATUS	(CVP_WRAPPER_BASE_OFFS + 0x80)

#define CVP_GCC_VIDEO_AXI1_CBCR		(0x32020)     /* Offset from GCC base (0x110000) */

#endif
