/* SPDX-License-Identifier: GPL-2.0 */
#ifndef _LINUX_HZOS_EXT_STATS_H
#define _LINUX_HZOS_EXT_STATS_H
/*
 *  Header containing hzos_ext stat definitions
 *
 *  Copyright (C) 2025 Meta Platforms, Inc. and affiliates
 */

#include <linux/bug.h>
#include <linux/sched.h>
#include <linux/types.h>

/*
 * All of this could be autogenerated using macros and tables if we used the
 * ANDROID_VENDOR_DATA_ARRAY embedded in struct task_struct to store the struct
 * hzos_ext, but if we did that, we wouldn't be able to view its contents
 * in bpftrace as the bpf verifier won't allow us to cast from a u64[] to a
 * struct hzos_ext.
 *
 * Instead, let's just manually add stat events for now. In order to add a new
 * stat event you must:
 *
 * 1. Add an entry to struct hzos_ext_stats in linux/hzos_ext_types.h
 * 2. Add an entry to this enum
 * 3. Add an entry to the switch statement in hzos_ext_stat_event_inc()
 * 4. Call hzos_ext_stat_event_inc() from wherever you need elsewhere in
 *    HzOS Ext.
 */
enum orchestrator_stat_event {
	NR_SRQ_PREV,
	NR_SRQ_SYNC,
	NR_SRQ_ANY,
};

#ifdef CONFIG_HZOS_EXT_STATS
static inline void hzos_ext_stat_event_inc(struct task_struct *p,
					       enum orchestrator_stat_event event)
{
	struct hzos_ext_stats *stats = &p->hzos_ext.stats;

	switch (event) {
		case NR_SRQ_PREV:
			stats->nr_srq_prev++;
			break;
		case NR_SRQ_SYNC:
			stats->nr_srq_sync++;
			break;
		case NR_SRQ_ANY:
			stats->nr_srq_any++;
			break;
		default:
			BUG();
	}
}
#else
static inline void hzos_ext_stat_event_inc(struct task_struct *p,
					       enum orchestrator_stat_event event)
{}
#endif

#endif /* _LINUX_HZOS_EXT_STATS_H */
