obj-$(CONFIG_SPECTRA_CAMERA) += cam_req_mgr/
obj-$(CONFIG_SPECTRA_CAMERA) += cam_utils/
obj-$(CONFIG_SPECTRA_CAMERA) += cam_core/
obj-$(CONFIG_SPECTRA_CAMERA) += cam_sync/
obj-$(CONFIG_SPECTRA_CAMERA) += cam_smmu/
obj-$(CONFIG_SPECTRA_CAMERA) += cam_cpas/
obj-$(CONFIG_SPECTRA_CAMERA) += cam_cdm/
obj-$(CONFIG_SPECTRA_CAMERA) += cam_isp/
obj-$(CONFIG_SPECTRA_CAMERA) += cam_sensor_module/
obj-$(CONFIG_SPECTRA_CAMERA) += cam_fastpath/

obj-$(CONFIG_SPECTRA_CAMERA_CUSTOM) += cam_cust/
obj-$(CONFIG_SPECTRA_CAMERA_FACE_DETECTION) += cam_fd/
obj-$(CONFIG_SPECTRA_CAMERA_ICP) += cam_icp/
obj-$(CONFIG_SPECTRA_CAMERA_JPEG) += cam_jpeg/
obj-$(CONFIG_SPECTRA_CAMERA_LRME) += cam_lrme/
