hts221-y := hts221_core.o
hts221-$(CONFIG_IIO_BUFFER) += hts221_buffer.o

obj-$(CONFIG_IIO_HTS221) += hts221.o
obj-$(CONFIG_IIO_HTS221_I2C) += hts221_i2c.o
obj-$(CONFIG_IIO_HTS221_SPI) += hts221_spi.o
