#ifndef COMPAT_AUTOCONF_INCLUDED
#define COMPAT_AUTOCONF_INCLUDED
/*
 * Automatically generated file, don't edit!
 * Changes will be overwritten
 */

#define CPTCFG_KERNEL_NAME "Linux"
#define CPTCFG_KERNEL_VERSION "v4.14.77-kong-android-RTM-rc8-0-g1c0d89e"
#define CPTCFG_VERSION "v4.14-rc2-1-70-g694b78f"
#define CPTCFG_WIRELESS 1
#define CPTCFG_NET_CORE 1
#define CPTCFG_EXPERT 1
#define CPTCFG_BP_MODULES 1
#define CPTCFG_BPAUTO_WANT_DEV_COREDUMP 1
#define CPTCFG_BPAUTO_BUILD_WANT_DEV_COREDUMP 1
#define CPTCFG_BPAUTO_REFCOUNT 1
#define CPTCFG_CFG80211_MODULE 1
#define CPTCFG_CFG80211_DEFAULT_PS 1
#define CPTCFG_CFG80211_INTERNAL_REGDB 1
#define CPTCFG_CFG80211_WEXT 1
#define CPTCFG_WLAN 1
#define CPTCFG_WLAN_VENDOR_BROADCOM 1
#define CPTCFG_BRCMUTIL_MODULE 1
#define CPTCFG_BRCMFMAC_MODULE 1
#define CPTCFG_BRCMFMAC_PROTO_BCDC 1
#define CPTCFG_BRCMFMAC_SDIO 1
#define CPTCFG_BRCM_TRACING 1
#define CPTCFG_BRCMDBG 1
#define CPTCFG_BRCMFMAC_ANDROID 1
#define CPTCFG_BRCM_INSMOD_NO_FW 1
#define CPTCFG_BRCMFMAC_CARD_DETECT 1
#define CPTCFG_BACKPORTED_WIRELESS 1
#define CPTCFG_BACKPORTED_NET_CORE 1
#define CPTCFG_BACKPORTED_EXPERT 1
#define CPTCFG_BACKPORTED_BP_MODULES 1
#define CPTCFG_BACKPORTED_BPAUTO_WANT_DEV_COREDUMP 1
#define CPTCFG_BACKPORTED_BPAUTO_BUILD_WANT_DEV_COREDUMP 1
#define CPTCFG_BACKPORTED_BPAUTO_REFCOUNT 1
#define CPTCFG_BACKPORTED_CFG80211_MODULE 1
#define CPTCFG_BACKPORTED_CFG80211_DEFAULT_PS 1
#define CPTCFG_BACKPORTED_CFG80211_INTERNAL_REGDB 1
#define CPTCFG_BACKPORTED_CFG80211_WEXT 1
#define CPTCFG_BACKPORTED_WLAN 1
#define CPTCFG_BACKPORTED_WLAN_VENDOR_BROADCOM 1
#define CPTCFG_BACKPORTED_BRCMUTIL_MODULE 1
#define CPTCFG_BACKPORTED_BRCMFMAC_MODULE 1
#define CPTCFG_BACKPORTED_BRCMFMAC_PROTO_BCDC 1
#define CPTCFG_BACKPORTED_BRCMFMAC_SDIO 1
#define CPTCFG_BACKPORTED_BRCM_TRACING 1
#define CPTCFG_BACKPORTED_BRCMDBG 1
#define CPTCFG_BACKPORTED_BRCMFMAC_ANDROID 1
#define CPTCFG_BACKPORTED_BRCM_INSMOD_NO_FW 1
#define CPTCFG_BACKPORTED_BRCMFMAC_CARD_DETECT 1
#endif /* COMPAT_AUTOCONF_INCLUDED */
