/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Copyright (c) 2024, Qualcomm Innovation Center, Inc. All rights reserved.
 */

#ifndef _DT_BINDINGS_CLK_QCOM_LPASS_AUDIO_CC_SCUBA_H
#define _DT_BINDINGS_CLK_QCOM_LPASS_AUDIO_CC_SCUBA_H

/* LPASS_AUDIO_CC clocks */
#define AUD_SLIMBUS_CLK_SRC					0
#define LPASS_AUDIO_CC_AUD_SLIMBUS_CLK				1
#define LPASS_AUDIO_CC_AUD_SLIMBUS_CORE_CLK			2
#define LPASS_AUDIO_CC_AUD_SLIMBUS_NPL_CLK			3
#define LPASS_AUDIO_CC_BUS_CLK					4
#define LPASS_AUDIO_CC_BUS_TIMEOUT_CLK				5
#define LPASS_AUDIO_CC_CDIV_RX_MCLK_DIV_CLK_SRC			6
#define LPASS_AUDIO_CC_CDIV_WSA_MCLK_DIV_CLK_SRC		7
#define LPASS_AUDIO_CC_CODEC_MEM0_CLK				8
#define LPASS_AUDIO_CC_CODEC_MEM1_CLK				9
#define LPASS_AUDIO_CC_CODEC_MEM2_CLK				10
#define LPASS_AUDIO_CC_CODEC_MEM3_CLK				11
#define LPASS_AUDIO_CC_CODEC_MEM_CLK				12
#define LPASS_AUDIO_CC_DIG_PLL					13
#define LPASS_AUDIO_CC_DIG_PLL_OUT_AUX				14
#define LPASS_AUDIO_CC_EXT_IF1_CLK_SRC				15
#define LPASS_AUDIO_CC_EXT_IF1_EBIT_CLK				16
#define LPASS_AUDIO_CC_EXT_IF1_IBIT_CLK				17
#define LPASS_AUDIO_CC_EXT_IF2_CLK_SRC				18
#define LPASS_AUDIO_CC_EXT_IF2_EBIT_CLK				19
#define LPASS_AUDIO_CC_EXT_IF2_IBIT_CLK				20
#define LPASS_AUDIO_CC_EXT_IF3_CLK_SRC				21
#define LPASS_AUDIO_CC_EXT_IF3_EBIT_CLK				22
#define LPASS_AUDIO_CC_EXT_IF3_IBIT_CLK				23
#define LPASS_AUDIO_CC_EXT_IF4_CLK_SRC				24
#define LPASS_AUDIO_CC_EXT_IF4_EBIT_CLK				25
#define LPASS_AUDIO_CC_EXT_IF4_IBIT_CLK				26
#define LPASS_AUDIO_CC_EXT_MCLK0_CLK				27
#define LPASS_AUDIO_CC_EXT_MCLK0_CLK_SRC			28
#define LPASS_AUDIO_CC_EXT_MCLK1_CLK				29
#define LPASS_AUDIO_CC_EXT_MCLK1_CLK_SRC			30
#define LPASS_AUDIO_CC_LPAIF_PCMOE_CLK				31
#define LPASS_AUDIO_CC_LPAIF_PCMOE_CLK_SRC			32
#define LPASS_AUDIO_CC_PLL					33
#define LPASS_AUDIO_CC_PLL_OUT_AUX				34
#define LPASS_AUDIO_CC_PLL_OUT_AUX2				35
#define LPASS_AUDIO_CC_PLL_OUT_AUX2_DIV_CLK_SRC			36
#define LPASS_AUDIO_CC_RX_MCLK_2X_CLK				37
#define LPASS_AUDIO_CC_RX_MCLK_CLK				38
#define LPASS_AUDIO_CC_RX_MCLK_CLK_SRC				39
#define LPASS_AUDIO_CC_SAMPLING_CLK				40
#define LPASS_AUDIO_CC_WSA_MCLK_2X_CLK				41
#define LPASS_AUDIO_CC_WSA_MCLK_CLK				42
#define LPASS_AUDIO_CC_WSA_MCLK_CLK_SRC				43
#define LPASS_AUDIO_CC_XPU2_CLIENT_CLK				44
#define LPASS_AON_CC_PLL_OUT_ODD_CLK				45

/* LPASS_AUDIO_CC resets */
#define LPASS_AUDIO_CC_EXT_IF1_BCR				0
#define LPASS_AUDIO_CC_EXT_IF2_BCR				1
#define LPASS_AUDIO_CC_EXT_IF3_BCR				2
#define LPASS_AUDIO_CC_EXT_IF4_BCR				3
#define LPASS_AUDIO_CC_EXT_MCLK0_BCR				4
#define LPASS_AUDIO_CC_EXT_MCLK1_BCR				5
#define LPASS_AUDIO_CC_PCM_DATA_OE_BCR				6
#define LPASS_AUDIO_CC_QCA_SLIMBUS_BCR				7
#define LPASS_AUDIO_CC_RX_MCLK_BCR				8
#define LPASS_AUDIO_CC_TX_MCLK_BCR				9
#define LPASS_AUDIO_CC_WSA_MCLK_BCR				10

#endif
