//
//
//

#ifndef __LANGDON_IOCTL_H_
#define __LANGDON_IOCTL_H_

#define DEVICE_NAME "langdon_fpga"
#define CLASS_NAME "langdon_fpga_class"
#define IOCTL_MAGIC 0xA2


// ------------------------------------------------
//    Langdon FPGA Register map
// ------------------------------------------------
#define LANGDON_FPGA_SYSTEM_REGISTERS_BASE (0x00000000)
#define LANGDON_FPGA_USER_REGISTERS_BASE (0x00800000)
#define LANGDON_FPGA_INTERRUPT_VECTOR_TABLE_BASE (0x00008000)  /* This is on BAR 2 */
// ------------------------------------------------
//    System Registers
// ------------------------------------------------
#define LANGDON_FPGA_REVISON_REGISTER (LANGDON_FPGA_SYSTEM_REGISTERS_BASE + 0x00)
#define LANGDON_FPGA_NUM_CHANNELS_REGISTER (LANGDON_FPGA_SYSTEM_REGISTERS_BASE + 0x04)
#define LANGDON_FPGA_DMA_CHANNEL_N_BASE_OFFSET_REGISTER (LANGDON_FPGA_SYSTEM_REGISTERS_BASE + 0x08)
#define LANGDON_FPGA_SW_INTERRUPT_REGISTER (LANGDON_FPGA_SYSTEM_REGISTERS_BASE + 0x8000000)

// ------------------------------------------------
//    DMA Channel Registers
// -----------------------------------------------

// NOTE: the base offset for the channel, read from LANGDON_FPGA_DMA_CHANNEL_N_BASE_OFFSET_REGISTER
//  must be added to this offset when accesing these registers

#define DMA_CHANNEL_REVISION_REGISTER (0x00)
#define DMA_CHANNEL_CONTROL_REGISTER (0x04)
#define DMA_CHANNEL_STATUS_REGISTER (0x08)
#define DMA_CHANNEL_PAT_SIZE_REGISTER (0x0c)
#define DMA_CHANNEL_PAT_MAX_SIZE_REGISTER (0x10)
#define DMA_CHANNEL_PAGE_SIZE_REGISTER (0x14)
#define DMA_CHANNEL_WP_REGISTER (0x18)
#define DMA_CHANNEL_RP_REGISTER (0x1c)
#define DMA_CHANNEL_FULL_THRESHOLD_REGISTER (0x20)
#define DMA_CHANNEL_EMPTY_THRESHOLD_REGISTER (0x24)
#define DMA_CHANNEL_WP_PROGRESS_REGISTER (0x28)
#define DMA_CHANNEL_RP_PROGRESS_REGISTER (0x2c)
#define DMA_CHANNEL_BURSTS_STARTED_REGISTER (0x30)
#define DMA_CHANNEL_BURSTS_FINISHED_REGISTER (0x34)
#define DMA_CHANNEL_THROTTLE_ADDRESS_REGISTER (0x38)
#define DMA_CHANNEL_THROTTLE_DATA_REGISTER (0x3c)
#define DMA_CHANNEL_THROTTLE_BRESP_REGISTER (0x40)
#define DMA_CHANNEL_THROTTLE_ADDRESS_MIN_REGISTER (0x44)
#define DMA_CHANNEL_THROTTLE_DATA_MIN_REGISTER (0x48)
#define DMA_CHANNEL_THROTTLE_BRESP_MIN_REGISTER (0x4c)
#define DMA_CHANNEL_THROTTLE_ADDRESS_MAX_REGISTER (0x50)
#define DMA_CHANNEL_THROTTLE_DATA_MAX_REGISTER (0x54)
#define DMA_CHANNEL_THROTTLE_BRESP_MAX_REGISTER (0x58)
#define DMA_CHANNEL_PAT_START (0x8000)

// channel control register bits
#define DMA_CHANNEL_PACKET_MODE_ENABLE (1<<17)
#define DMA_CHANNEL_USE_UDP_HEADERS (1<<16)
#define DMA_CHANNEL_AXI_MAX_BURST_LENGTH (0xFF<<8)
#define DMA_CHANNEL_NEAR_EMPTY_IRQ_ENABLE (1<<5)
#define DMA_CHANNEL_NEAR_FULL_IRQ_ENABLE (1<<4)
#define DMA_CHANNEL_TLAST_IRQ_ENABLE (1<<3)
#define DMA_CHANNEL_SHUTDOWN_REQ (1<<2)
#define DMA_CHANNEL_DIRECTION (1<<1)
#define DMA_CHANNEL_ENABLE (1<<0)

// channel status register bits
#define DMA_CHANNEL_STATUS_BUSY (1<<0)
#define DMA_CHANNEL_STATUS_SHUTDOWN_STATUS (3<<1)
#define DMA_CHANNEL_STATUS_C2H_UNEXPECTED_TLAST (1<<3)
#define DMA_CHANNEL_STATUS_C2H_BRESP_CAPTURE (3<<4)
#define DMA_CHANNEL_STATUS_H2C_BRESP_CAPTURE (3<<6)

// ------------------------------------------------
//    User Logic Registers
// ------------------------------------------------
#define LANGDON_USER_CONTROL (LANGDON_FPGA_USER_REGISTERS_BASE + 0x00)
#define LANGDON_H2C_STATUS (LANGDON_FPGA_USER_REGISTERS_BASE + 0x04)
#define LANGDON_INTERRUPT_ENABLE_REGISTER (LANGDON_FPGA_USER_REGISTERS_BASE + 0x08)
#define LANGDON_INTERRUPT_STATUS_REGISTER (LANGDON_FPGA_USER_REGISTERS_BASE + 0x0c)
#define LANGDON_C2H0_WORD_COUNTER (LANGDON_FPGA_USER_REGISTERS_BASE + 0x10)
#define LANGDON_C2H1_WORD_COUNTER (LANGDON_FPGA_USER_REGISTERS_BASE + 0x14)
#define LANGDON_C2H2_WORD_COUNTER (LANGDON_FPGA_USER_REGISTERS_BASE + 0x18)
#define LANGDON_C2H3_WORD_COUNTER (LANGDON_FPGA_USER_REGISTERS_BASE + 0x1c)
#define LANGDON_H2C0_WORD_COUNTER (LANGDON_FPGA_USER_REGISTERS_BASE + 0x20)
#define LANGDON_H2C1_WORD_COUNTER (LANGDON_FPGA_USER_REGISTERS_BASE + 0x24)
#define LANGDON_H2C2_WORD_COUNTER (LANGDON_FPGA_USER_REGISTERS_BASE + 0x28)
#define LANGDON_H2C3_WORD_COUNTER (LANGDON_FPGA_USER_REGISTERS_BASE + 0x2c)
#define LANGDON_PACKET_GENERATOR_0_LENGTH (LANGDON_FPGA_USER_REGISTERS_BASE + 0x30)
#define LANGDON_PACKET_GENERATOR_1_LENGTH (LANGDON_FPGA_USER_REGISTERS_BASE + 0x34)
#define LANGDON_PACKET_GENERATOR_2_LENGTH (LANGDON_FPGA_USER_REGISTERS_BASE + 0x38)
#define LANGDON_PACKET_GENERATOR_3_LENGTH (LANGDON_FPGA_USER_REGISTERS_BASE + 0x3c)
#define LANGDON_PACKET_GENERATOR_0_COUNT (LANGDON_FPGA_USER_REGISTERS_BASE + 0x40)
#define LANGDON_PACKET_GENERATOR_1_COUNT (LANGDON_FPGA_USER_REGISTERS_BASE + 0x44)
#define LANGDON_PACKET_GENERATOR_2_COUNT (LANGDON_FPGA_USER_REGISTERS_BASE + 0x48)
#define LANGDON_PACKET_GENERATOR_3_COUNT (LANGDON_FPGA_USER_REGISTERS_BASE + 0x4c)

// UDP control register bits
#define UDP_CONTROL_CHANNEL_PAIR_0_MODE (3<<0) /* CH4-CH0 0 = loopback, 1 = udp, 2 = core 0 -> core 1 loopback  */
#define UDP_CONTROL_CHANNEL_PAIR_1_MODE (3<<2) /* CH5-CH1 0 = loopback, 1 = udp, 2 = core 0 -> core 1 loopback  */
#define UDP_CONTROL_CHANNEL_PAIR_2_MODE (3<<4) /* CH6-CH2 0 = loopback, 1 = udp, 2 = core 0 -> core 1 loopback  */
#define UDP_CONTROL_CHANNEL_PAIR_3_MODE (3<<6) /* CH7-CH3 0 = loopback, 1 = udp, 2 = core 0 -> core 1 loopback  */
#define UDP_C2H_PACKET_GEN_0_ENABLE (1<<8) /* CH0 */
#define UDP_C2H_PACKET_GEN_1_ENABLE (1<<9) /* CH1 */
#define UDP_C2H_PACKET_GEN_2_ENABLE (1<<10) /* CH2 */
#define UDP_C2H_PACKET_GEN_3_ENABLE (1<<11) /* CH3 */
#define UDP_C2H_PACKET_GEN_0_MODE (3<<12)  /* CH0 0 = RAW, 1 = NOT USED, 2 = PACKET/no UDP headers, 3 = PACKET + headers */
#define UDP_C2H_PACKET_GEN_1_MODE (3<<14)  /* CH1 0 = RAW, 1 = NOT USED, 2 = PACKET/no UDP headers, 3 = PACKET + headers */
#define UDP_C2H_PACKET_GEN_2_MODE (3<<16)  /* CH2 0 = RAW, 1 = NOT USED, 2 = PACKET/no UDP headers, 3 = PACKET + headers */
#define UDP_C2H_PACKET_GEN_3_MODE (3<<18)  /* CH3 0 = RAW, 1 = NOT USED, 2 = PACKET/no UDP headers, 3 = PACKET + headers */
#define UDP_C2H_PACKET_GEM_MODE_0_BIT (12)

// UDP status register bits
#define LANGDON_FPGA_UDP_STATUS_PACKET_GEN_0_RUNNING (1<<0)
#define LANGDON_FPGA_UDP_STATUS_PACKET_GEN_1_RUNNING (1<<1)
#define LANGDON_FPGA_UDP_STATUS_PACKET_GEN_2_RUNNING (1<<2)
#define LANGDON_FPGA_UDP_STATUS_PACKET_GEN_3_RUNNING (1<<3)
#define LANGDON_FPGA_UDP_STATUS_DATA_CHECKER_0_ERROR (1<<4)
#define LANGDON_FPGA_UDP_STATUS_DATA_CHECKER_1_ERROR (1<<5)
#define LANGDON_FPGA_UDP_STATUS_DATA_CHECKER_2_ERROR (1<<6)
#define LANGDON_FPGA_UDP_STATUS_DATA_CHECKER_3_ERROR (1<<7)

// interrupts mapping bits
#define SOFTWARE_INTERRUPT_3 (1<<15)
#define SOFTWARE_INTERRUPT_2 (1<<14)
#define SOFTWARE_INTERRUPT_1 (1<<13)
#define SOFTWARE_INTERRUPT_0 (1<<12)
#define CHANNEL_7_NEAR_FULL_INTERRUPT (1<<11)
#define CHANNEL_6_NEAR_FULL_INTERRUPT (1<<10)
#define CHANNEL_5_NEAR_FULL_INTERRUPT (1<<9)
#define CHANNEL_4_NEAR_FULL_INTERRUPT (1<<8)
#define CHANNEL_3_NEAR_FULL_INTERRUPT (1<<7)
#define CHANNEL_3_TLAST_INTERRUPT (1<<6)
#define CHANNEL_2_NEAR_FULL_INTERRUPT (1<<5)
#define CHANNEL_2_TLAST_INTERRUPT (1<<4)
#define CHANNEL_1_NEAR_FULL_INTERRUPT (1<<3)
#define CHANNEL_1_TLAST_INTERRUPT (1<<2)
#define CHANNEL_0_NEAR_FULL_INTERRUPT (1<<1)
#define CHANNEL_0_TLAST_INTERRUPT (1<<0)

// ------------------------------------------------
//    BAR 2 registers
// ------------------------------------------------
#define LANGDON_FPGA_INTERRUPT_VECTOR_0_OFFSET (LANGDON_FPGA_INTERRUPT_VECTOR_TABLE_BASE)
#define LANGDON_FPGA_INTERRUPT_VECTOR_ENTRY_LEN (0x10)
#define LANGDON_FPGA_INTERRUPT_VECTOR_ADDRESS_LOW_OFFSET (0x00)
#define LANGDON_FPGA_INTERRUPT_VECTOR_ADDRESS_HIGH_OFFSET (0x04)
#define LANGDON_FPGA_INTERRUPT_VECTOR_MSG_OFFSET (0x08)
#define LANGDON_FPGA_INTERRUPT_VECTOR_CONTROL_OFFSET (0x0C)

// IOCTLS
#define IOCTL_READ _IOR(IOCTL_MAGIC, 1, uint64_t)
#define IOCTL_WRITE _IOW(IOCTL_MAGIC, 2, uint64_t)
#define IOCTL_GET_BUFFER _IOR(IOCTL_MAGIC, 3, uint64_t)
#define IOCTL_GET_VERSION _IOR(IOCTL_MAGIC, 4, uint64_t)
#define IOCTL_READ_REGISTER _IOR(IOCTL_MAGIC, 5, uint64_t)
#define IOCTL_WRITE_REGISTER _IOW(IOCTL_MAGIC, 6, uint64_t)
#define IOCTL_OPEN_CHANNEL _IOWR(IOCTL_MAGIC, 7, uint64_t)
#define IOCTL_CLOSE_CHANNEL _IOW(IOCTL_MAGIC, 8, uint64_t)
#define IOCTL_USER_INTERRUPT_WAIT _IOR(IOCTL_MAGIC, 9, uint64_t)
#define IOCTL_USER_INTERRUPT_CANCEL_WAIT _IOW(IOCTL_MAGIC, 10, uint64_t)
#define IOCTL_SHUTDOWN_CHANNEL _IOW(IOCTL_MAGIC, 11, uint64_t)


typedef enum _PKT_GEN_MODE {
    RAW = 0,
    NOT_USED,
    PACKET_NO_HEADERS,
    PACKET_UPD_HEADERS
} PACKET_GEN_MODE;

// -----------------------------------------
// Langdon driver typedefs
// -----------------------------------------
typedef struct _DRIVER_VERSION_STRUCT {
    int Major;
    int Minor;
    int Patch;
} DRIVER_VERSION_STRUCT;

typedef struct _DRIVER_REGISTER_ACCESS_STRUCT {
    uint32_t offset;
    uint32_t data;
    uint32_t bar;
} DRIVER_REGISTER_ACCESS_STRUCT;

typedef struct _DMA_CHANNEL_SETUP_STRUCT {
    int channel;
    uint32_t number_of_PAT_entries;
    int channel_mode; /* 0 = RAW, 1 = PKT */
    int udp_headers; /* 0 = Headers are stripped, 1 = Headers are passed to UDP */
    uint32_t near_empty_threshold;
    uint32_t near_full_threshold;
    uint32_t tlast_enable;
    uint32_t burst_len;
} DMA_CHANNEL_SETUP_STRUCT;


#endif // __LANGDON_IOCTL_H_
