obj-$(CONFIG_SYNCBOSS)			+= spi_fastpath.o
obj-$(CONFIG_SYNCBOSS_DEBUG)	+= syncboss_debugfs.o
obj-$(CONFIG_SYNCBOSS)			+= syncboss_sequence_number.o
obj-$(CONFIG_SYNCBOSS)			+= syncboss_spi.o
obj-$(CONFIG_SYNCBOSS)			+= syncboss_sysfs.o
