obj-$(CONFIG_META_HAMMERHEAD)	+= netinfo.o
obj-$(CONFIG_META_FLORIAN)      += netinfo.o
obj-$(CONFIG_META_GREATWHITE)   += netinfo.o
obj-$(CONFIG_META_BLUEWHITE)    += netinfo.o
netinfo-y	:= session_table.o msg_queue.o latency.o pkt_gen.o stats.o
